entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true

http:
  routers:
    backend:
      rule: "Host(`backend.localhost`)"
      service: backend_service
      entryPoints:
        - web

    frontend:
      rule: "Host(`localhost`)"
      service: frontend_service
      entryPoints:
        - web

    jobpilot:
      rule: "Host(`localhost`) && PathPrefix(`/jobpilot`)"
      service: frontend_service
      entryPoints:
        - web
      middlewares:
        - frontend-auth

    frontend-unsecured:
      rule: 'PathRegexp(`^/([a-z]{2})?/?$`) || PathRegexp(`^(/[a-z]{2})?/auth`) || PathRegexp(`^/(_next|static)`) || Path(`/__nextjs_original-stack-frame`)'
      priority: 99
      service: frontend_service
      middlewares:
        - frontend-auth

  services:
    backend_service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
        sticky:
          cookie:
            name: "session_token"
            secure: false
            httpOnly: true
            sameSite: "Lax"
            domain: ".localhost"

    frontend_service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
        sticky:
          cookie:
            name: "session_token"
            secure: false
            httpOnly: true
            sameSite: "Lax"
            domain: ".localhost"

  middlewares:
    frontend-auth:
      forwardAuth:
        address: "http://backend.localhost/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-User"

log:
  level: DEBUG
